### ISSUE TITLE
 Lock npm dependencies: shrinkwrap or yarn?

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#12]
> The npm dependencies should be locked at known working versions. Application developers can then upgrade npm packages selectively in a controlled fashion as required.
> 
> This would apply to both the generator itself, and the generated output project.
> 
> There are two possible approaches to this that I am aware of:
> 
> 1. Use `npm shrinkwrap` to produce a `npm-shrinkwrap.json` file
> 2. Switch to `yarn` which has it's own `yarn.lock` by default
> 
> I would normally favour option 2: `yarn` however, the tabris-js.com online build tool would need to detect that `yarn` is being used in place of npm

Original issue: https://github.com/eclipsesource/generator-tabris-js/issues/16

**Comment by mpost** [comment]
npm 5 has a feature called `package-lock.json`. This could also be an option when shrinkwrap is not used.

Release notes: http://blog.npmjs.org/post/161081169345/v500
