### ISSUE TITLE
Tabris CLI should print a warning for unsupported Cordova versions

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js-cli#14]
It was decided to consume the globally installed `cordova` module to prevent having this big dependency (~45 MB) installed twice (once as a global module and once as a tabris-cli dependency) for users who already have it installed globally.

It should at least be checked whether the globally installed `cordova` module is compatible with the Tabris.js platforms. In case it isn't, a warning should be output to the console.

**Comment by mpost** [comment]
While i fully agree that warnings should be printed, in fact there have to be errors. Not every cli version is compatible with each other. Eg. you can not build with tabris-android platform based on cordova 6.1 and the latest cordova cli. You _have_ to use a later version.

The only real solution is to create a dependency to cordova from the cli. This solves a lot of problems people are having when building locally. The two clis are very closely intertwined and we should remove the burden to figure out what belongs together from the user.
