### ISSUE TITLE
Document (in CLI) how to handle platform specific arguments

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#16]
In cordova cli the platform specific properties can be passed by separating them via `--`, e.g. `cordova build windows --release -- --archs="arm"`. It's unclear how to do this with tabris cli, the help printed by `tabris` is only tells me `build [options] <platform> [platformOpts...]`. It doesn't say anything about `--` or what the `platformOpts` are... (arguments passed to cordova cli directly? Or the platform build?)

**Comment by cpetrov** [comment]
They are passed as is to Cordova: http://cordova.apache.org/docs/en/6.x/reference/cordova-cli/index.html#platform-specific-options

`tabris build -h` shows following information about platformOpts:

```
  [platformOpts...]:	platform-specific options passed to cordova
```

I think it should mention how exactly they are passed to Cordova. The README should also mention `[platformOpts...]` and link to the Cordova docs.

**Comment by cpetrov** [comment]
`platformOpts` was a confusing parameter. It was only used for Android builds and was obsoleted by `--cordova-build-config`, which also supports configuration for other platforms than Android. That's why it was removed from Tabris CLI in 36dac101017103d8f60c1f5ccaba70da022fe627.
