### ISSUE TITLE
Support cordova prepare

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#17]
`cordova prepare` can be useful if you need a native project that can be opened in a IDE or built with native tools. (We may or may not need this for building windows store apps.) We should support this as `tabris prepare` just like we support `cordova run` and `cordova build`.

**Comment by cpetrov** [comment]
We have decided not to implement a command supporting `cordova prepare` for simplicity. The native SDK project artifacts will be created after running `tabris build <platform>`.
