### ISSUE TITLE
Allow launching TypeScript projects via `tabris start`

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#19]
Currently, going in to a TypeScript project generated by `tabris init` and writing `tabris serve` does not work correctly, the app is not (re-) transpiled. 

It would be cool if a new command `tabris start` would work for these kind of projects as well in some manner.

**Comment by cpetrov** [comment]
`tabris serve` was changed to execute the _build_ script in the package.json of the app before serving it.
