### ISSUE TITLE
build should execute npm install

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-cli#2]
I tried to execute `tabris build` in a project I freshly checked out from github and got an error message about `tsc -p .`. It turns out that I never executed `npm install` in my project before I executed `tabris build`.

I would suggest to always execute `npm install` when a user tries to build with the cli.

If I execute `npm install` once all the following invocations are super fast (nothing to do for npm):
```
$ time npm install

real	0m0.718s
user	0m0.744s
sys	0m0.080s
```

At least the cli should detect that `npm install` was never executed and present a better error message something along the lines of "Please execute `npm install` before building the project.".

**Comment by mpost** [comment]
`tabris build` will always perform an `npm install --production` for you.

**Comment by mpost** [comment]
Are you on the latest `master` version?

**Comment by jonek** [comment]
Installed from npm.

**Comment by mpost** [comment]
The requested feature is already implemented and will be released on npm together with Tabris.js 2.
