### ISSUE TITLE
Platform download feature does not support nightly platforms

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js-cli#22]
Currently the installed version of `tabris` is used to get the platform using the Connect service `https://tabrisjs.com/api/v1/downloads/cli/<version>/<platform>`.

When using release channel `nightly` as JS module version, version `2.0.0-rc2-dev.20170707` of `tabris` is resolved by npm. The Connect service does not resolve the nightly platform when receiving argument `<version>` in the format `2.0.0-rc2-dev.20170707`. In this case a `404` status is returned.

Solution suggestions: 

1. Decide whose responsibility is it to match JS module versions with platform versions.

    Either the Connect service `api/v1/downloads/cli` can be changed to resolve proper `nightly` platforms for `dev` JS module versions or the CLI can be changed to call the service with `<version>` `2.x-nightly` for such versions.

2. Another possibility would be to release nightly platforms with the same version numbers as the `tabris` module. In this case, compatibility with the `dev` JS module version can be ensured. 

In any case, nightly platforms should be cached in a different way than other platforms. Caching a nightly platform every day is not desired. Nightly platforms should either not be cached at all or they should be only cached for the day corresponding to their version timestamp (older nightlies may be cleaned up when a build is run).

**Comment by ralfstx** [comment]
As different nightly builds are often incompatible to one another, I think that (2) is the only option. Only if the platform matches the tabris version *precisely*, we can guarantee working build results.

That means that the server needs to make nightly versions available with file names that include timestamps like `2.0.0-rc2-dev.20170707`.

I agree that older platform version should be cleaned up based on their timestamp.

**Comment by cpetrov** [comment]
The platform service has been adjusted to support serving nightly platforms compatible with the Tabris module version.
