### ISSUE TITLE
Print a message to explain how to obtain build key

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js-cli#28]
The message currently printed to ask for the build key is [apparently not clear enough](https://stackoverflow.com/questions/45440363/tabris-js-getting-started-fail):

    Build key (https://tabrisjs.com/settings/account): _

We should print a more detailed message, e.g.:

    Please enter your build key. You'll find it on your profile page
    on https://tabrisjs.com/ when you're logged in.
    Build key: _

**Comment by cookieguru** [comment]
I think an explanation of _what_ and/or _why_ would be useful as well.  It is important to distinguish this from the various other types of keys used in the build process.
