### ISSUE TITLE
Remove Windows 10 Support

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#38]
Windows 10 app development is no longer supported in Tabris.js 3.x

**Comment by ishigo1987** [comment]
Why you stop the windows 10 support in tabris 3.x

**Comment by tbuschto** [comment]
@ishigo1987 Sorry for the late response. Windows 10 support will not be in 3.x (for now) primarily due to the decline of Windows 10 Mobile and the Universal Windows Platform. If these are making a comeback we may consider migrating the windows platform to 3.x as well.

**Comment by tbuschto** [comment]
This issue was fixed in commit f0e88027239e5ec644f085a3bcda562d4a8bd622
