### ISSUE TITLE
Use same IP for QR-Code and WebSocket

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-cli#39]
The mobile client should always use the same IP for the websocket as it uses to retrieve the app. This makes it unnecessary to put the full websocket URL in the boot file, only the port number is required there.

The same heuristic should be used to identify the correct IP address once and then us it for QR code and websocket.

**Comment by cpetrov** [comment]
@ahmadov I think this is the case already? https://github.com/eclipsesource/tabris-js-cli/blob/da45c2ffb2a692c6c74ef28ed3befd0a0e5cc5d3/resources/debugClient.js#L12

Please reopen if there is additional work I'm missing that needs to be done.
