### ISSUE TITLE
Support older major versions

### ISSUE THREAD

**Issue by patrykmol** [eclipsesource/tabris-js-cli#40]
Building 2.x project with cli from master (3.0) results in an error `App uses incompatible tabris version: 2.6.0, 3.x.x required.`. Major older versions should be supported in newer cli versions as well. Current behaviour is very inconvenient.

**Comment by cpetrov** [comment]
Following version check should be removed: https://github.com/eclipsesource/tabris-js-cli/blob/46d3e7797b855ec023616460f639665520dd4a39/src/services/TabrisApp.js#L57

**Prerequisites:**
Install Cordova CLI dynamically: https://github.com/eclipsesource/tabris-js-cli/issues/51
Disable Tabris CLI 3.x features when building 2.x apps: https://github.com/eclipsesource/tabris-js-cli/issues/52

**Comment by josiahking** [comment]
How long will it take to resolve this issue?

**Comment by cookieguru** [comment]
@josiahking Looks like 4 days

**Comment by cpetrov** [comment]
@josiahking @cookieguru just resolved; the change will be avaliable in tomorrow's nightly.

**Comment by josiahking** [comment]
Does the beta version now dupport older version also?

**Comment by cookieguru** [comment]
@josiahking Yes; you'll need to install the nightly:
```bash
npm install -g tabris-cli@nightly
```

**Comment by josiahking** [comment]
@cookieguru That works thanks.
@cpetrov Is there a way to make tabris use specific version during initialization of project?
Just the way we can select between javascript or typescript.
Since the build now supports older version.

**Comment by cookieguru** [comment]
@josiahking You'd need to temporarily downgrade the cli to do that.

**Comment by cpetrov** [comment]
@josiahking This is a valid use case since we now support building and serving 2.x apps with the 3.x CLI. I have opened #62.

**Comment by josiahking** [comment]
@cookieguru Oh i get it, you have to upgrade or downgrade the cli version manually. Thanks.
I was thinking is something that is possible after installing tabrid-cli. Just remember that we can only have one install per machine.

**Comment by josiahking** [comment]
@cookieguru Oh i get it, you have to upgrade or downgrade the cli version manually. Thanks.
I was thinking is something that is possible after installing tabrid-cli. Just remember that we can only have one install per machine.
