### ISSUE TITLE
QR code links to undefined when no WiFi connections exist

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js-cli#45]
`require('node-wifi').getCurrentConnections()` will return `[]` if there are no active WiFi connections.  Thus the `then` block in [`getFirstWifiInterface()`](https://github.com/eclipsesource/tabris-js-cli/blob/951dfdbaa49cca68b2f5469e17ab39cbde5151d5/src/services/ServerInfo.js#L43) is executed and ends up returning `undefined`.

**Comment by jonek** [comment]
Good catch. We will try to improve this.
