### ISSUE TITLE
Update Cordova CLI dependency

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js-cli#49]
Currently, Tabris.js CLI uses an outdated Cordova CLI dependency (6.5.0). It should be updated to the latest version (currently 8) for the Tabris.js 3 release. It fixes various bugs and offers new features and support for modern Cordova plugins.

Note that an update from 6.5.0 to 8 would introduce several changes, which may require taking action for some of the Cordova plugins written for Tabris.js:

* Cordova plugins will now be installed by `npm`, similarly to using the transitional `--fetch` flag in 6.5.0. This enables the flexibility of using npm package features like [scripts](https://docs.npmjs.com/misc/scripts) in Cordova plugins. 

* A side effect of using `npm` for installing the plugins is that using plugin specs with subdirectories is not supported anymore (i.e. [`:subdir` syntax](https://cordova.apache.org/docs/en/6.x/reference/cordova-cli/index.html#plugin-spec)), so Tabris.js plugins which use subdirectories would have to be reworked.

* Plugins and platforms need to have a package.json file.

**Comment by mpost** [comment]
I think we were aware of the subfolder restriction and package.json requirement. Do you know of a plugin that would require a change?

**Comment by cpetrov** [comment]
@mpost Only this plugin misses a package.json: https://github.com/eclipsesource/tabris-plugin-cloud-backup. I will update it.

Note: this new requirement has to be documented in the Tabris.js migration guide.
