### ISSUE TITLE
tabris 2.0.0rc1 environment

### ISSUE THREAD

**Issue by ghost** [eclipsesource/tabris-js-cli#5]
Please pull advice for the environment 
- node version
- cordova version
- android sdk components
- xcode version

what is the current build server environment?
my local bahaviour differs from build server.
My local environment:
osx 10.12.4
node 6.10.3
cordova 7.0.0
android build tools 25.0.3
android tools r25.2.3
android cmake 3.6.3
android sdk tools 26.0.2
xcode 8.3.2

**Comment by cookieguru** [comment]
If you run a build and look at the detailed output it should answer most of the questions for you.

**Comment by ghost** [comment]
my personal solution was
https://github.com/eclipsesource/tabris-js/issues/1308#issuecomment-301210408
so I close the issue
