### ISSUE TITLE
Support generating 2.x projects with 3.x CLI

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js-cli#62]
Currently it is not possible to generate 2.x projects with 3.x CLI. The only option to do so currently is downgrading the CLI to 2.x, which is cumbersome. Since closing https://github.com/eclipsesource/tabris-js-cli/issues/40, Tabris CLI 3.x should support 2.x apps as well and this includes generating 2.x apps. A prompt can be made available during the project generation to specify the CLI version (3.x can be preselected).

**Comment by cookieguru** [comment]
Added in https://github.com/eclipsesource/generator-tabris-js/commit/f7de9f8742718e471fd655b3f607445776bfecce
