### ISSUE TITLE
Add command line parameter to allow customization of URL in QR code

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-cli#63]
In certain situations it is not possible to reach the URL that is encoded in the QR code from a mobile device. In this situations it would be handy to be able to specify a custom URL when executing `tabris serve -l`.

For example: `tabris serve -l --url http://custom-url:1234`

**Comment by cookieguru** [comment]
`--external` option added in 2c0de40764fef96089308e9de784c51232d025cb
