### ISSUE TITLE
"tabris serve" shows prompt even when not using "-i"

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-cli#65]
When executing the latest version of tabris-cli (tabris-cli@3.0.0-rc1-dev.20190424) using
```tabris serve -l``` and NOT using `-i` the output shows a blue prompt: `>>`

I would expect to see this prompt only when I provide the `-i` command line flag.
To me it indicates that the active process wants me to type some input.

**Comment by cpetrov** [comment]
Cannot reproduce with the latest CLI. Please reopen in case this issue persists for you!
