### ISSUE TITLE
Stopping "tabris serve" requires Ctrl-c two times

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-js-cli#66]
To stop a running `tabris serve` I am required to type Ctrl-c two times.

I would expect it to terminate right after the first Ctrl-c.

This was observed in version tabris-cli@3.0.0-rc1-dev.20190424

**Comment by jonek** [comment]
Maybe this is related to issue #65

**Comment by cpetrov** [comment]
Cannot reproduce with the latest CLI. Please reopen in case this issue persists for you!
