### ISSUE TITLE
Ecstatic Dependency Version

### ISSUE THREAD

**Issue by Tunapop** [eclipsesource/tabris-js-cli#67]
Having trouble getting the tabris-cli installed, and I just found out that currently only the latest version of ecstatic is available via npm: "4.1.2"

npm install -g tabris-cli
__
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ecstatic@^2.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'tabris-cli'
npm ERR! notarget 

Assuming the cause of this is the tabris-cli ecstatic dependency version. Any thoughts?

**Comment by cookieguru** [comment]
https://github.com/jfhbrook/node-ecstatic/issues/255

**Comment by cookieguru** [comment]
Ideally the author will republish the old version(s) but in the meantime `tabris-cli` could be updated.  Only thing is everyone would need to update their cli to the next version the next time they install it

**Comment by jonek** [comment]
We will fix it ASAP. Thanks for reporting.

**Comment by cookieguru** [comment]
@jonek The author has [backported the fix to ecstatic 2.x](https://github.com/jfhbrook/node-ecstatic/issues/255#issuecomment-489101365) as 2.2.2 so the existing versions depending on `^2.1.0` should work fine and 5da4450f3a34cfc60fceaf36f52424baf2b36890 can be reverted.

**Comment by cookieguru** [comment]
@jonek Will need to revert 66be537d1d1257d4b413780d5ad44214514b7a63; npm just [republished the old versions](https://github.com/jfhbrook/node-ecstatic/issues/255#issuecomment-489259794) which has subsequently made [2.2.2 disappear](https://www.npmjs.com/package/ecstatic).

**Comment by jonek** [comment]
@cookieguru What has happened :scream:? I don't get it - how can npm revert backports of a security fix and re-publish old unsecure versions?

**Comment by cookieguru** [comment]
🤷‍♂️ if enough people complain to npm anything is possible!?  That happened with left pad.
