### ISSUE TITLE
Check for latest versions of generator and cli

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js-cli#7]
When the installed `tabris-cli` and/or `generator-tabris-js` modules are outdated, the CLI will create projects from outdated templates or build apps with an outdated format.

Let the CLI check if newer versions of these modules are available and display a warning if so.

**Comment by cpetrov** [comment]
`generator-tabris-js` is now a dependency of `tabris-cli`. `tabris-cli` will print a warning if it is outdated.
