### ISSUE TITLE
Incorrect behavior when using "tabris build"

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-js-cli#78]
```
Using cordova-fetch for C:\Users\fax1ty\.tabris-cli\platforms\android\3.2.1
Failed to fetch platform C:\Users\fax1ty\.tabris-cli\platforms\android\3.2.1
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
```

The installer does not check if such a directory exists and does not install the platform if it does not exist. Why is it trying to install the platform from local files?

**Comment by cookieguru** [comment]
Actually it does check to see if it exists: https://github.com/eclipsesource/tabris-js-cli/blob/master/src/services/PlatformsCache.js#L24
The platform has to be downloaded locally; this is what actually performs the build

**Comment by cpetrov** [comment]
@fax1ty Could you please check the contents of `C:\Users\fax1ty\.tabris-cli\platforms\android\3.2.1` and `C:\Users\fax1ty\.tabris-cli\platforms`? Maybe downloading or unzipping failed in some way before it was attempted to copy the platform to `C:\Users\fax1ty\.tabris-cli\platforms\android\3.2.1`. 

Deleting the folder `C:\Users\fax1ty\.tabris-cli\platforms\android\3.2.1` and starting another build should fix the problem.

**Comment by fax1ty** [comment]
@cpetrov I restarted the build and now it downloaded the platform version 3.3.0 instead of 3.2.1 (I built using the latest version, but still somehow downloaded the old one)

Everything works now

![image](https://user-images.githubusercontent.com/26363214/76997483-ca525800-696c-11ea-9939-9dc08338b419.png)
