### ISSUE TITLE
Implement web socket to connect to device console

### ISSUE THREAD

**Issue by ralfstx** [eclipsesource/tabris-js-cli#8]
It would be very helpful to have the console output of a connected device available on the development machine, e.g. for copy and paste. It would be even more useful being able to type statements on the dev machine and have them executed on the device.

Let's implement a web socket that clients can connect to, send console input to the clients, receive console output and print it to the console.

**Comment by mpost** [comment]
While i agree that it would be handy to have the output in the tabris serve command, you can currently read the log output from Android when the tabris app is build in debug mode via the [`logcat`](https://developer.android.com/studio/command-line/logcat.html) command.

**Comment by tbuschto** [comment]
We can use JSON for this. For server -> client we probably need at least an evaluate command like `{eval: "console.log('foo');"}`. For client-> server we need to support the console methods (`debug`, `info`, `log`, `warn`, `error`) and the eval result, e.g. `{result: 23}`. I wonder we need some kind of handshake. Also, should the clients implement this natively or in JS (`boot.js`)?

**Comment by tbuschto** [comment]
Implemented as of 3.0.0-beta1
