### ISSUE TITLE
Generate .tabrisignore

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js-cli#9]
Depending on the project setup, some files should not end up in the final tabris app. This includes tests, README.md, .vscode (other IDE configs as well), .npmrc, js/tslint, tsconfig.json, .gitignore and in case of typescript only "src". Also possibly build scripts (like Gruntfile), but there are currently none created by default.

**Comment by cpetrov** [comment]
Done in eclipsesource/generator-tabris-js@41a7e67
